### ISSUE TITLE
the roadmap for official support

### ISSUE THREAD

**Issue by DhavalRepo18** [opendatahub-io-contrib/ai-on-openshift#21]
I am looking at the current repo which is recently created. May i know what is the path for official support?

**Comment by guimou** [comment]
What do you mean exactly by "official support"?
Red Hat Openshift Data Science is a fully supported product you can buy from Red Hat.
Open Data Hub is an open source project thats is not supported.
On this site you will find different recipes that may include projects or products that may or may not be supported.

**Comment by guimou** [comment]
@DhavalRepo18 Did that answer your question?

**Comment by DhavalRepo18** [comment]
@guimou Thanks for the clarification.
