### ISSUE TITLE
Can not open Red hat OpenShift AI dashboard

### ISSUE THREAD

**Issue by yangqbo** [opendatahub-io-contrib/ai-on-openshift#94]
Application is not available
The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

Possible reasons you are seeing this page:

The host doesn't exist. Make sure the hostname was typed correctly and that a route matching this hostname exists.
The host exists, but doesn't have a matching path. Check if the URL path was typed correctly and that the route was created using the desired path.
Route and path matches, but all pods are down. Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.

**Comment by erwangranger** [comment]
Hello, 

it seems that you are having an issue with the application OpenShift AI Dashboard. 
This repository is just related to content around AI-related things you can do on OpenShift AI, ODH, and OpenShift. 
It's not a general support channel. 

I suggest you contact Red Hat [Support](https://access.redhat.com/support/cases/#/case/new/open-case?caseCreate=true) to open a Case. This way, you will get the proper level of support and follow-through required to resolve your issue. 

I hope this helps.

**Comment by yangqbo** [comment]
Hello,
Thank you for your rational suggestion! I will try to looking for help from the  Red Hat Support.
Thank you!
